// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMoRbm5xp0FNaA9w0dp4Vth3PX6xzyv_U',
    appId: '1:527667604872:web:9705957def0faf9e995e3d',
    messagingSenderId: '527667604872',
    projectId: 'carspot-444ed',
    authDomain: 'carspot-444ed.firebaseapp.com',
    storageBucket: 'carspot-444ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU_tpi4bh4VlGat_oHfqS3X3AgoYtxKJc',
    appId: '1:527667604872:android:9610f6763067f35d995e3d',
    messagingSenderId: '527667604872',
    projectId: 'carspot-444ed',
    storageBucket: 'carspot-444ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPmjMdPo_zviJnW3Nh_cWDENJKlOU6Vk',
    appId: '1:527667604872:ios:e5710fb212c66fab995e3d',
    messagingSenderId: '527667604872',
    projectId: 'carspot-444ed',
    storageBucket: 'carspot-444ed.appspot.com',
    iosClientId: '527667604872-l4tkvbnngvmqnqt7tka4hu01bktbcekr.apps.googleusercontent.com',
    iosBundleId: 'com.example.carspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzPmjMdPo_zviJnW3Nh_cWDENJKlOU6Vk',
    appId: '1:527667604872:ios:e5710fb212c66fab995e3d',
    messagingSenderId: '527667604872',
    projectId: 'carspot-444ed',
    storageBucket: 'carspot-444ed.appspot.com',
    iosClientId: '527667604872-l4tkvbnngvmqnqt7tka4hu01bktbcekr.apps.googleusercontent.com',
    iosBundleId: 'com.example.carspot',
  );
}
